Update release.yml  — compile.js

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -4,20 +4,19 @@ on:
   workflow_dispatch:
   pull_request:
     types: [closed]
-    branches:    
+    branches:
       - main
 
 jobs:
   check-env:
     runs-on: ubuntu-latest
     steps:
-      - name: "Check is DIPLODOC_STORAGE_BUCKET secret exists"
-        env:
-          storage-bucket: ${{ vars.DIPLODOC_STORAGE_BUCKET }}
-        if: ${{ env.storage-bucket == '' }}
+      - name: "Check if DIPLODOC_STORAGE_BUCKET is set"
         run: |
-          echo "::error:: The variable \"DIPLODOC_STORAGE_BUCKET\" has not been made; please check that all necessary secrets and variables are installed or follow the link https://diplodoc.com/quickstart"
-          exit 1
+          if [ -z "${{ vars.DIPLODOC_STORAGE_BUCKET }}" ]; then
+            echo "::error:: Missing required variable DIPLODOC_STORAGE_BUCKET. Follow https://diplodoc.com/quickstart to configure your project."
+            exit 1
+          fi
 
   build:
     needs: check-env
@@ -25,44 +24,26 @@ jobs:
     runs-on: ubuntu-latest
     permissions: write-all
     steps:
-      - name: Checkout repository
+      - name: Checkout
         uses: actions/checkout@v3
 
-      - name: Set up Node.js 20.18.1
+      - name: Setup Node.js
         uses: actions/setup-node@v3
         with:
           node-version: 20.18.1
 
-      - name: Install Diplodoc CLI
-        run: npm install -g @diplodoc/cli@latest
-
-      - name: Build documentation
-        run: yfm build ./docs -o ./_docs-build
-
-      - name: Check that _docs-build exists
-        run: |
-          if [ ! -d "./_docs-build" ]; then
-            echo "::error:: Build output folder '_docs-build' not found. Build might have failed."
-            exit 1
-          fi
-
-      - name: Upload build artifacts
-        uses: actions/upload-artifact@v4
+      - name: Build with Diplodoc Action
+        uses: diplodoc-platform/docs-build-action@v3
         with:
-          name: build-output-md
-          include-hidden-files: true
-          path: ./_docs-build
-          retention-days: 1
-          if-no-files-found: error
-          compression-level: 6
-          overwrite: false
+          revision: "${{ github.sha }}"
+          src-root: "./docs"
 
   upload:
     needs: build
     runs-on: ubuntu-latest
     permissions: write-all
     steps:
-      - name: Upload to storage
+      - name: Upload to S3
         uses: diplodoc-platform/docs-upload-action@v1
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
@@ -76,7 +57,7 @@ jobs:
     needs: upload
     runs-on: ubuntu-latest
     steps:
-      - name: Release
+      - name: Release on Diplodoc
         uses: diplodoc-platform/docs-release-action@v2
         with:
           revision: "${{ github.sha }}"
