Update release.yml — сборка YFM

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -11,12 +11,13 @@ jobs:
   check-env:
     runs-on: ubuntu-latest
     steps:
-      - name: "Check if DIPLODOC_STORAGE_BUCKET is set"
+      - name: "Check if DIPLODOC_STORAGE_BUCKET variable exists"
+        env:
+          storage_bucket: ${{ vars.DIPLODOC_STORAGE_BUCKET }}
+        if: ${{ env.storage_bucket == '' }}
         run: |
-          if [ -z "${{ vars.DIPLODOC_STORAGE_BUCKET }}" ]; then
-            echo "::error:: Missing required variable DIPLODOC_STORAGE_BUCKET. Follow https://diplodoc.com/quickstart to configure your project."
-            exit 1
-          fi
+          echo "::error:: The variable \"DIPLODOC_STORAGE_BUCKET\" is missing; check your secrets and variables or visit https://diplodoc.com/quickstart"
+          exit 1
 
   build:
     needs: check-env
@@ -24,26 +25,39 @@ jobs:
     runs-on: ubuntu-latest
     permissions: write-all
     steps:
-      - name: Checkout
+      - name: Checkout repository
         uses: actions/checkout@v3
 
-      - name: Setup Node.js
+      - name: Setup Node.js 20.x
         uses: actions/setup-node@v3
         with:
-          node-version: 20.18.1
+          node-version: 20
 
-      - name: Build with Diplodoc Action
-        uses: diplodoc-platform/docs-build-action@v3
+      - name: Install Diplodoc CLI globally
+        run: npm install -g @diplodoc/cli@latest
+
+      - name: Build documentation with yfm
+        run: yfm build ./docs -o ./_docs-build
+
+      - name: Upload build artifacts
+        uses: actions/upload-artifact@v4
         with:
-          revision: "${{ github.sha }}"
-          src-root: "./docs"
+          name: build-output-md
+          path: ./_docs-build
+          retention-days: 1
+          if-no-files-found: warn
 
   upload:
     needs: build
     runs-on: ubuntu-latest
     permissions: write-all
     steps:
-      - name: Upload to S3
+      - name: Download build artifacts
+        uses: actions/download-artifact@v3
+        with:
+          name: build-output-md
+
+      - name: Upload to storage
         uses: diplodoc-platform/docs-upload-action@v1
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
@@ -57,10 +71,10 @@ jobs:
     needs: upload
     runs-on: ubuntu-latest
     steps:
-      - name: Release on Diplodoc
+      - name: Release
         uses: diplodoc-platform/docs-release-action@v2
         with:
-          revision: "${{ github.sha }}"
+          revision: ${{ github.sha }}
           storage-bucket: ${{ vars.DIPLODOC_STORAGE_BUCKET }}
           storage-access-key-id: ${{ secrets.DIPLODOC_ACCESS_KEY_ID }}
           storage-secret-access-key: ${{ secrets.DIPLODOC_SECRET_ACCESS_KEY }}
